In [47]:
#loading dfs
import os
import pandas as pd
from pathlib import Path
p2 = Path("..") / "1_Source_Files" / "df_final_web_data_pt_1.txt"
df2 = pd.read_csv(p2, sep=",", encoding="utf-8", engine="python") 

p3 = Path("..") / "1_Source_Files" / "df_final_web_data_pt_2.txt"
df3 = pd.read_csv(p3, sep=",", encoding="utf-8", engine="python") 

pC = Path("..") / "1.1_Clean_Files" / "df_final_experiment_clients_clean.csv"
dfC = pd.read_csv(pC, sep=",", encoding="utf-8", engine="python")

In [48]:
#visual check 1.1_Clean_Files\df_final_experiment_clients_clean.csv
df2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [49]:
#visual check
df3.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [50]:
#merging vertically dfs into df4
df4 = pd.concat([df2, df3], ignore_index=True)
df4 = df4.drop_duplicates()
df4.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [51]:
#visual check 
df4.info()

<class 'pandas.DataFrame'>
Index: 744641 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     744641 non-null  int64
 1   visitor_id    744641 non-null  str
 2   visit_id      744641 non-null  str
 3   process_step  744641 non-null  str
 4   date_time     744641 non-null  str
dtypes: int64(1), str(4)
memory usage: 34.1 MB

In [52]:
#visual check
df4.isnull()

        client_id  visitor_id  visit_id  process_step  date_time
0           False       False     False         False      False
1           False       False     False         False      False
2           False       False     False         False      False
3           False       False     False         False      False
4           False       False     False         False      False
...           ...         ...       ...           ...        ...
755400      False       False     False         False      False
755401      False       False     False         False      False
755402      False       False     False         False      False
755403      False       False     False         False      False
755404      False       False     False         False      False

[744641 rows x 5 columns]

In [53]:
#cleaning and norilizing data
df4['client_id'] = df4['client_id'].astype(str).str.strip()
df4['date_time'] = pd.to_datetime(df4['date_time'], errors='coerce')

In [54]:
#cleaning and norilizing data
for text in ['visitor_id', 'visit_id', 'process_step']:
    if text in df4.columns:
        df4[text] = df4[text].astype(str).str.strip()

In [55]:
output_path = "../1.1_Clean_Files/df4_final_web_data_clean.csv"

df4.to_csv(output_path, index=False)

In [56]:
#visual check
df4 = df4.dropna(subset=['client_id', 'date_time'], how='any')

In [57]:
#visual check
print(df4.head())
print('rows:', len(df4))

  client_id            visitor_id                      visit_id process_step  \
0   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
1   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
2   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
3   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
4   9988021  580560515_7732621733  781255054_21935453173_531117       step_3

            date_time
0 2017-04-17 15:27:07
1 2017-04-17 15:26:51
2 2017-04-17 15:19:22
3 2017-04-17 15:19:13
4 2017-04-17 15:18:04
rows: 744641

In [58]:
#visual check for understanding
id_val = 9988021
date_val = "2017-04-17" 
id_s = str(id_val)
target = pd.to_datetime(date_val).date()
result = df4[(df4['client_id'] == id_s) & (df4['date_time'].dt.date == target)]
print(result)

  client_id            visitor_id                      visit_id process_step  \
0   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
1   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
2   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
3   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
4   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
5   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
6   9988021  580560515_7732621733  781255054_21935453173_531117       step_1
7   9988021  580560515_7732621733  781255054_21935453173_531117        start

            date_time
0 2017-04-17 15:27:07
1 2017-04-17 15:26:51
2 2017-04-17 15:19:22
3 2017-04-17 15:19:13
4 2017-04-17 15:18:04
5 2017-04-17 15:17:15
6 2017-04-17 15:17:01
7 2017-04-17 15:16:22

In [59]:
#visual check for understanding
id_val = 763412
#id_val = 6019349
date_val = "2017-06-06" 
id_s = str(id_val)
target = pd.to_datetime(date_val).date()
result = df4[df4['client_id'] == id_s]
display(result)

,client_id,visitor_id,visit_id,process_step,date_time
343141,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
343322,763412,601952081_10457207388,275115855_33219234532_879732,confirm,2017-06-02 09:37:04
343323,763412,601952081_10457207388,275115855_33219234532_879732,step_3,2017-06-02 09:35:50
343324,763412,601952081_10457207388,275115855_33219234532_879732,step_2,2017-06-02 09:35:13
343325,763412,601952081_10457207388,275115855_33219234532_879732,step_1,2017-06-02 09:34:41
343326,763412,601952081_10457207388,275115855_33219234532_879732,start,2017-06-02 09:33:47

In [60]:
#visual check for understanding
id_val = 9988021
date_val = "2017-04-17" 
id_s = str(id_val)
target = pd.to_datetime(date_val).date()
result2 = df4[df4['process_step'] == "confirm" ]
display(result2)

,client_id,visitor_id,visit_id,process_step,date_time
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05
13,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:03
14,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:01
15,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:28:52
24,1982004,618934751_10082078917,132494692_73738638511_70823,confirm,2017-04-17 12:02:42
...,...,...,...,...,...
755362,1462269,756274405_34153014475,903240226_7790404978_158729,confirm,2017-06-03 11:49:32
755368,9563467,358754208_29929976792,898272434_72817818195_285148,confirm,2017-06-04 10:21:23
755375,2443347,818414719_69544570654,148166449_67114410166_524360,confirm,2017-05-30 19:18:18
755376,9895983,473024645_56027518531,498981662_93503779869_272484,confirm,2017-06-15 19:55:09
755384,9668240,388766751_9038881013,922267647_3096648104_968866,confirm,2017-05-24 19:07:35

In [61]:

dfC.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [62]:
client_id = 9988021
id_s = str(client_id)
target = pd.to_datetime(date_val).date()
result = dfC[dfC['client_id'] == id_s]
display(result)

Empty DataFrame
Columns: [client_id, Variation]
Index: []

In [63]:
dfC['client_id'] = dfC['client_id'].astype(str)
df4C = df4.merge(dfC[['client_id','Variation']], on='client_id', how='left')

In [64]:
#visual check for understanding
id_val = 763412
#id_val = 6019349
date_val = "2017-06-06" 
id_s = str(id_val)
target = pd.to_datetime(date_val).date()
result = df4C[df4C['client_id'] == id_s]
display(result)

,client_id,visitor_id,visit_id,process_step,date_time,Variation
341046,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00,NaN
341225,763412,601952081_10457207388,275115855_33219234532_879732,confirm,2017-06-02 09:37:04,NaN
341226,763412,601952081_10457207388,275115855_33219234532_879732,step_3,2017-06-02 09:35:50,NaN
341227,763412,601952081_10457207388,275115855_33219234532_879732,step_2,2017-06-02 09:35:13,NaN
341228,763412,601952081_10457207388,275115855_33219234532_879732,step_1,2017-06-02 09:34:41,NaN
341229,763412,601952081_10457207388,275115855_33219234532_879732,start,2017-06-02 09:33:47,NaN

In [ ]:
dfC.duplicated

In [ ]:
Pollob