In [ ]:
#loading dfs
import os
import pandas as pd
from pathlib import Path
p2 = Path("..") / "1_Source_Files" / "df_final_web_data_pt_1.txt"
df2 = pd.read_csv(p2, sep=",", encoding="utf-8", engine="python") 

p3 = Path("..") / "1_Source_Files" / "df_final_web_data_pt_2.txt"
df3 = pd.read_csv(p3, sep=",", encoding="utf-8", engine="python")

In [ ]:
#visual check
df2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [ ]:
#visual check
df3.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [ ]:
#merging vertically dfs into df4
df4 = pd.concat([df2, df3], ignore_index=True)
df4 = df4.drop_duplicates()
df4.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [ ]:
#visual check
df4.info()

<class 'pandas.DataFrame'>
Index: 744641 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     744641 non-null  int64
 1   visitor_id    744641 non-null  str
 2   visit_id      744641 non-null  str
 3   process_step  744641 non-null  str
 4   date_time     744641 non-null  str
dtypes: int64(1), str(4)
memory usage: 34.1 MB

In [ ]:
#visual check
df4.isnull()

        client_id  visitor_id  visit_id  process_step  date_time
0           False       False     False         False      False
1           False       False     False         False      False
2           False       False     False         False      False
3           False       False     False         False      False
4           False       False     False         False      False
...           ...         ...       ...           ...        ...
755400      False       False     False         False      False
755401      False       False     False         False      False
755402      False       False     False         False      False
755403      False       False     False         False      False
755404      False       False     False         False      False

[744641 rows x 5 columns]

In [ ]:
#cleaning and norilizing data
df4['client_id'] = df4['client_id'].astype(str).str.strip()
df4['date_time'] = pd.to_datetime(df4['date_time'], errors='coerce')

In [ ]:
#cleaning and norilizing data
for text in ['visitor_id', 'visit_id', 'process_step']:
    if text in df4.columns:
        df4[text] = df4[text].astype(str).str.strip()

In [ ]:
#visual check
df4 = df4.dropna(subset=['client_id', 'date_time'], how='any')

In [ ]:
#visual check
print(df4.head())
print('rows:', len(df4))

  client_id            visitor_id                      visit_id process_step  \
0   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
1   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
2   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
3   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
4   9988021  580560515_7732621733  781255054_21935453173_531117       step_3

            date_time
0 2017-04-17 15:27:07
1 2017-04-17 15:26:51
2 2017-04-17 15:19:22
3 2017-04-17 15:19:13
4 2017-04-17 15:18:04
rows: 744641

In [ ]:
#visual check for understanding
id_val = 9988021
date_val = "2017-04-17" 
id_s = str(id_val)
target = pd.to_datetime(date_val).date()
result = df4[(df4['client_id'] == id_s) & (df4['date_time'].dt.date == target)]
print(result)

  client_id            visitor_id                      visit_id process_step  \
0   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
1   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
2   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
3   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
4   9988021  580560515_7732621733  781255054_21935453173_531117       step_3
5   9988021  580560515_7732621733  781255054_21935453173_531117       step_2
6   9988021  580560515_7732621733  781255054_21935453173_531117       step_1
7   9988021  580560515_7732621733  781255054_21935453173_531117        start

            date_time
0 2017-04-17 15:27:07
1 2017-04-17 15:26:51
2 2017-04-17 15:19:22
3 2017-04-17 15:19:13
4 2017-04-17 15:18:04
5 2017-04-17 15:17:15
6 2017-04-17 15:17:01
7 2017-04-17 15:16:22