In [9]:
import pandas as pd
import numpy as np


import os
print(os.getcwd())        # full path of the current directory
print(os.listdir('.'))    # list files/folders in that directory

df = pd.read_csv("/Users/huss/data-processing/week5/group_project/project_2/1_Source_Files/df_final_experiment_clients.txt")
df

/Users/huss/data-processing/week5/group_project/project_2/2_Python_Notebook
['project.ipynb', 'Stuck_Husseim.ipynb', '.ipynb_checkpoints']

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

In [35]:
df["Variation"] = df["Variation"].fillna("empty")
df["Variation"].replace({"NaN": pd.NA})
df["Variation"].value_counts()

Variation
Test       26968
Control    23532
empty      20109
Name: count, dtype: int64

In [16]:
df.drop_duplicates()

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

0           Test
1           Test
2        Control
3           Test
4        Control
          ...
70604      empty
70605      empty
70606      empty
70607      empty
70608      empty
Name: Variation, Length: 70609, dtype: object

In [34]:
print(df.head(5))
print(df.tail(5))
print(df.info())
print(df.info(memory_usage="deep"))
print(df.describe())
print(df.describe(include="all"))
print(df.shape)
print(df.dtypes)
print(df.columns)
print(df.index)
print(df.values)
print(df.empty)
print(df.ndim)
print(df.size)
print(df.memory_usage(deep=True))
print(df.T)

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control
       client_id Variation
70604    2443347     empty
70605    8788427     empty
70606     266828     empty
70607    1266421     empty
70608    9895983     empty
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  70609 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  70609 non-null  object
dtypes: int64(1), object(1)
memory usage: 4.2 MB
None
          client_id
count  7.060900e+04
mean   5.004992e+06
std    2.877278e+06
min    1.690000e+02
25%    2.519329e+06
50%    5.016978e+06
75%    7.483085e+06
max    9.999839e+06
           client_id Variation
count   7.060900e+04     70609
unique           NaN         3
top              NaN      Test
freq             NaN     26968
mean    5.004992e+06       NaN
std     2.877278e+06       NaN
min     1.690000e+02       NaN
25%     2.519329e+06       NaN
50%     5.016978e+06       NaN
75%     7.483085e+06       NaN
max     9.999839e+06       NaN
(70609, 2)
client_id     int64
Variation    object
dtype: object
Index(['client_id', 'Variation'], dtype='object')
RangeIndex(start=0, stop=70609, step=1)
[[9988021 'Test']
 [8320017 'Test']
 [4033851 'Control']
 ...
 [266828 'empty']
 [1266421 'empty']
 [9895983 'empty']]
False
2
141218
Index            132
client_id     564872
Variation    3832982
dtype: int64
             0        1        2        3        4        5        6      \
client_id  9988021  8320017  4033851  1982004  9294070  9466803  3170143
Variation     Test     Test  Control     Test  Control     Test     Test

             7        8        9      ...    70599    70600    70601    70602  \
client_id  6651403  5887227  2105948  ...  5217934  1020453  9722009  3897324
Variation  Control     Test  Control  ...    empty    empty    empty    empty

            70603    70604    70605   70606    70607    70608
client_id  687702  2443347  8788427  266828  1266421  9895983
Variation   empty    empty    empty   empty    empty    empty

[2 rows x 70609 columns]